kartoza/docker-geoserver

Dockerfile

Added a little logic that will fetch the JAI and JAI ImageIO tar files if they are not available locally in the resources folder.

Add a logic to fetch local files of JAI and JAI ImageIO

---

Dockerfile

while building were thrown an errors like this "mv: cannot stat ‘/tmp/gs_plugin/*.jar’: No such file or directory"

Modified Dockerfile

---

Dockerfile
README.md

Fix download path for saving downloads in the image

---

Dockerfile
README.md
build.sh
scripts/setup.sh

download war file from url by passing `--build-arg WAR_URL=<URL>` to docker build command

download war file from url provided by the user

---

Dockerfile
README.md
scripts/entrypoint.sh

Move GEOSERVER_OPTS to entrypoint.sh

---

Dockerfile
build.sh
scripts/entrypoint.sh
scripts/update_passwords.sh

- introduces geoserver user
- remove tomcate default apps by default
- increase GeoServer Version to 2.16.0

GeoServer 2.16.0

---

scripts/setup.sh

This commit intends to fix Issue #138 Local GeoServer War

Unzipping local geoserver-<version>.zip before continuing

---

Dockerfile
docker-compose.yml
scripts/entrypoint.sh
scripts/start.sh

* Install Microsoft fonts, fix duplicates in entrypoint script

Install microsoft fonts

---

Dockerfile
README.md
scripts/setup.sh
scripts/start.sh

Fixes #163 
Fixes #162 
Fixes #160

Update documentation, fix some tomcat issues

---

Dockerfile
README.md
build.sh
build_data/community_plugins.txt
build_data/stable_plugins.txt
scripts/setup.sh
scripts/start.sh

* Fix URL
* Upgrade tomcat base image
* Upgrade to the latest geoserver

Merge develop to master

---

Dockerfile
build.sh
scripts/entrypoint.sh
scripts/setup.sh
scripts/start.sh
scripts/update_passwords.sh

* Use kartoza recipe for Geonode install.  Based on logic from https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/geoserver/docker-entrypoint.sh

Docker image for SPC geonode 

---

scripts/setup.sh

I have changed the location of the jai and imageio installation location based on this.
https://geoserver.geo-solutions.it/educational/en/install_run/jai_io_install.html

changed jai and imageio installation location

---

Dockerfile

Signed-off-by: Iosefa Percival <ipercival@gmail.com>
give permissions to copy to fonts directory

give permissions to fonts directory

---

build_data/web.xml

added Authorization Header for CORS to get preflight working

Authorization Header for CORS preflight

---

scripts/update_passwords.sh

* move random password set after file env check

Random password #256

---

scripts/env-data.sh
scripts/functions.sh
scripts/start.sh
scripts/update_passwords.sh

Fixed unusable <ENV>_FILE variables

---

scripts/entrypoint.sh
scripts/env-data.sh

Adding variables for language, region, and country and set geotools.localDateTimeHandling to true

Adding variables for language, region, and country

---

build_data/context.xml
clustering/docker-compose.yml
scripts/entrypoint.sh
scripts/env-data.sh
scripts/functions.sh
scripts/setup.sh
scripts/start.sh
scripts/update_passwords.sh
upgrade_geoserver_version.sh

Superseed https://github.com/kartoza/docker-geoserver/pull/371

Cluster configs

---

Dockerfile
scripts/setup.sh
scripts/start.sh

docker improvements

---

README.md

add windows build instructions to readme
