Dockerfile

This Dockerfile sets the ENV but doesn't create the directory, leading to geoserver outputting things like these in the logs:
```
ERROR [storage.DefaultStorageFinder] - Found System environment variable GEOSERVER_DATA_DIR set to /opt/geoserver/data_dir , but this path does not exist
...
WARN [geoserver.global] - Found System environment variable GEOSERVER_DATA_DIR set to /opt/geoserver/data_dir , but this path does not exist
...
INFO [geoserver.global] - Falling back to embedded data directory: /usr/local/tomcat/webapps/geoserver/data
```

Add mkdir for GEOSERVER_DATA_DIR

---

Dockerfile

The wget commands need to put the JAI/imageio zips into the resources directory (if not available), otherwise subsequent mv command fails. Reproduce by doing a docker build without the local tars available.

Fix for JAI/imageio download bug

---

Dockerfile

When asterisks are quoted, they are treated as literal!

Fix plugin install globbing bug

---

Dockerfile
README.md
build.sh
controlflow.properties
download.sh
resources/plugins/README.txt

* Added a download script to install plugins in Geoserver. The script should be run before building the image. Some common plugins should be preinstalled in the image (ie control-flow, GDAL, WPS, Image pyramid)
* Added GDAL data directory and environment variables to ensure when a user installs the Gdal plugins Geoserver recognizes them.
* Moved the java environment settings to the docker file so that the image contains built-in optimizations.
* Modified build script so that when building the image locally you only specify the GeoServer version once in the download script and it changes all occurrences in other files. Example Dockerfile and download.sh.
* Added more instructions in the readme including how to use a persistent storage with sample data from GeoServer war file.
* Added a …

Added extra options for geoserver

---

scripts/update_passwords.sh

When re-building the image with a newer Geoserver version, the `update_passwords.sh` script might fail, because the new Geoserver version uses a newer version of jasypt.
This PR fixes that, by not hardcoding the jasypt jar to 1.8, but instead looking for any jasypt jar located in `$CLASSPATH`.

Fix problems arising from hardcoded jasypt path

---

scripts/update_passwords.sh

unpatched causes error:
```
svc-geoserver_1  | cp: cannot stat '/opt/geoserver/data_dir/security/usergroup/default/users.xml': No such file or directory
svc-geoserver_1  | /scripts/update_passwords.sh: line 35: /opt/geoserver/data_dir/security/usergroup/default/users.xml: No such file or directory
svc-geoserver_1  | cat: /opt/geoserver/data_dir/security/usergroup/default/users.xml.orig: No such file or directory
```

bug fix: update_passwords ignores env data_dir

---

docker-env/geoserver.env

When having geoserver behind a proxy (such as nginx). The need to have that domain added to the CSRF whitelist is necessary for all of the
forms to work when POSTing data back to geoserver. Geoserver offers the
GEOSERVER_CSRF_WHITELIST property to be set via web.xml, -D arg via JVM,
or by environment variable. Since this is a containerized version of geoserver,
using an environment variable is optimal for following cloud native
development best practices (aka 12-factor).
Reference: https://docs.geoserver.org/stable/en/user/security/webadmin/csrf.html

Add GEOSERVER_CSRF_WHITELIST to geoserver.env

---

README.md
scripts/entrypoint.sh

Fixes #127 by not running `update_passwords.sh` if the environment variable EXISTING_DATA_DIR is set.

Added option for EXISTING_DATA_DIR

---

scripts/update_passwords.sh

Minor changes to the update_passwords.sh script to handle setting a custom admin username as an admin in geoserver. Regarding issue: #148

Edit the roles.xml file to have the custom geoserver admin user set as an admin

---

Dockerfile
README.md

This is to support 9.0.36 without breaking earlier versions. I have moved definition of JAVA_HOME to an argument of the docker container. If webapps/manager is in the dist folder it is copied across.
This request is now for the develop branch.

Add support for Tomcat/9.0.36 #165

---

README.md
scripts/entrypoint.sh
scripts/env-data.sh

We have found that sometimes some of the environment variables set to get GeoServer running have sensitive information in them like credentials or passwords. Having a way to set those environment variables from Docker secret files can be helpful. This code follows a pattern we found in another kartoza GitHub repository kartoza/docker-postgis.

Allow environment variables to be set from Docker secret files (similar to kartoza/docker-postgis)

---

.env
Dockerfile
README.md

Allow specifying arbitrary UID/GID for geoserveruser as some existing geoserver data dirs might have existing uid/gid ownership that can't be changed.

Allow specifying arbitrary UID/GID for geoserveruser

---

.env
Dockerfile

Currently the `IMAGE_TAG` variable in the Dockerfile and .env file are set to 'jdk11-openjdk-slim-buster'
The Tomcat docker image maintainers updated that tag to Tomcat 10, which is breaking this build process (see https://github.com/kartoza/docker-geoserver/issues/301#issuecomment-922669052)
This PR pins the tomcat tag to Tomcat 9 in order to avoid breaking the build process when the tomcat version changes for a tag.
I purposely made this pr against the master branch in order to patch the broken build process. If necessary I can recreate it against the develop branch.

Pin tomcat image tag to tomcat 9

---

Dockerfile
docker-compose.yml

This Pull Request closes #282. It makes sure that no `VOLUME` is defined inside of the Dockerfile so that the user of this image has full control over how they want to define persistency in their Geoserver stack. 
This makes it possible for someone to allow persistency at built vs persistency at runtime (see the ticket for a better explanation). 
----
I changed the docker-compose to have the same behaviour as the `VOLUME` did. As this docker-compose is just a suggestion for someone using this image, I do not believe this is that important.

282 Remove Volume definition in Dockerfile and apply persistent behaviour to docker-compose

---

.env
Dockerfile
docker-compose-build.yml
scripts/setup.sh

* Add build arg `STABLE_PLUGIN_BASE_URL=https://liquidtelecom.dl.sourceforge.net` because older archived versions fetched plugins from https://master.dl.sourceforge.net
We need to build the following images
* 2.16.5 , 2.17.5, 2.18.5 with the build ARG  `STABLE_PLUGIN_BASE_URL=https://master.dl.sourceforge.net`
* 2.19.4,2.20.2 should build fine with the current scripts and args

fix build url for older versions

---

.env
README.md
build_data/index.jsp
scripts/env-data.sh
scripts/start.sh

Include a new environment variable `ROOT_WEBAPP_REDIRECT` to issue a redirect from the root webapp ("/") to geoserver webapp ("/geoserver/web").
This only applies when `TOMCAT_EXTRAS=false`
Fixes #319

Allow redirection to GeoServer webapp when TOMCAT_EXTRAS=false

---

docker-compose-nginx.yml
docker-compose.yml

This fixes a minor indent issue which confused me for a while, as it was causing a YAML parsing error when I tried adding a new `volumes` item without realizing that it wasn't at the same indent level.

Fix item indent in YAML files

---

README.md

`EXISTING_DATA_DIR=true` suggests that setting it to false will run the password
init script, when it has to be unset entirely in order for the script to run.

readme: clarify how EXISTING_DATA_DIR works

---

.env
Dockerfile
README.md

Just noticed the convenient `upgrade_geoserver_version.sh` script after I already made the changes :)
Would it be possible to trigger a Docker release after this is successfully merged?

Upgraded GeoServer from version 2.20.2 to 2.20.3

---

README.md

I have added some notes in the Readme file after the closed issue [#378](https://github.com/kartoza/docker-geoserver/issues/378) regarding the local build of the image for MacOS M1 Chip.
Thank you for the help,
Kind Regards,

Added some additional notes  to run local image in MacOS M1 Chip

---

.env
Dockerfile
README.md
upgrade_geoserver_version.sh

This PR closes #393 and fixes the upgrade script so that it can be used with MacOS.
After the PR nothing in the behavior of Geoserver should be changed. Since there is a minor version update of Spring included in the patch version update from Geoserver 2.20.3 to 2.20.4 one should be attentive for bug reports in the Geoserver project concerning this change.

Upgrade GeoServer from version 2.20.3 to 2.20.4 (closes #393)

---

README.md

Github no longer allows you to pull from `git:` addresses, it needs to be `https:`

Fix github url

---

scripts/env-data.sh

During last merge with conflict resolution, USE_DATETIME_IN_SHAPEFILE default value was removed. Bringing back.

missing USE_DATETIME_IN_SHAPEFILE default value
